### ISSUE TITLE
Cannot import name 'ResBus'

### ISSUE THREAD

**Issue by eosram** [openego/ego.io#9] opened 2016-12-06 17:37 UTC
Hey,

I'm getting the following error message runnig hv_grid_lopf.py taken from the examples folder of ego.powerflow.

  File "<ipython-input-1-e282938cc7a4>", line 2, in <module>
    from egopowerflow.tools.io import get_timerange, import_components, import_pq_sets,    add_source_types, create_powerflow_problem

  File "/home/ulf/ego.powerflow/egopowerflow/tools/io.py", line 7, in <module>
    from egoio.db_tables.calc_ego_mv_powerflow import ResBus, ResLine, ResTransformer

ImportError: cannot import name 'ResBus' 

I did find a temporary workaround though. In the rev-list of git there are some commits containing the class definition of ResBus and I checked out on one of them. Do you have any ideas how to fix this? Is ResBus intended to exist on the master branch?

**Comment by gplssm** [comment] 2016-12-07 16:05
Sorry, for the delayed answer!

By accident, new introduced db table class definitions were added in another branch. I cherry-picked them by 74564d5700c1fffa32db62d04d45a16a750fd255

@s3pp if this solves your issue, please close this one.

**Comment by ulfmueller** [comment] 2016-12-20 13:04
so far the issue is still pending.

a short-term workaround for the hv application is to cd to the ego.io repository and then execute:

`git rev-list --all | xargs git grep ResBus `

and then checkout the master branch to the commit with the first number which appears.

`git checkout <commit> `

**Comment by ulfmueller** [comment] 2016-12-20 13:17
@gplssm : the workaround is clearly not optimal. Is there only minor fixing or cherry picking to do? did you just miss a cherry? or is it more complicated? Tell us if someone can support on that (I would need some explanation because I do not know in detail what is the problem)...

**Comment by simnh** [comment] 2016-12-20 13:56
thank, seemed to help!

**Comment by gplssm** [comment] 2016-12-20 14:16
With latest version I don't have problem to run the critical line of code

```
from egoio.db_tables.calc_ego_mv_powerflow import ResBus, ResLine, ResTransformer
```

@ulfmueller , @s3pp , @simnh have installed https://github.com/openego/ego.powerflow/releases/latest? As this version comes with [latest version of ego.io](https://github.com/openego/ego.io/releases/latest) this issue should be fixed.

**Comment by simnh** [comment] 2016-12-20 14:20
Sorry, yeah will the master checkout it actually work. I was on an old commit in ego.io but on a new one in ego.powerflow.... easy t oget confused with all the repos and developing stuff only every few month ;) Thanks !!

**Comment by ulfmueller** [comment] 2016-12-20 14:41
You are right @gplssm ! it works. Sorry for that confusion - I was not up-to-date.

**Closed as completed by ulfmueller** 2016-12-20 14:41 UTC
Labels: bug, help wanted, question
